version: '3.8'

services:
  app:
    #build: .
    image: ghcr.io/atcomputing/webrag-demo
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434

